import os
from html.parser import HTMLParser


class TrackingHTMLParser(HTMLParser):
    """HTMLParser subclass that tracks comments and parse errors."""

    def __init__(self):
        super().__init__()
        self.errors = []
        self.comments = []

    def handle_comment(self, data):
        self.comments.append(data)

    def error(self, message):
        # HTMLParser.error is called on parse errors.
        self.errors.append(message)


def test_index_html_validity():
    """Load index.html and ensure it parses without errors and contains the AI disclaimer."""
    html_path = os.path.join(os.path.dirname(__file__), os.pardir, "index.html")
    with open(html_path, "r", encoding="utf-8") as f:
        content = f.read()

    parser = TrackingHTMLParser()
    parser.feed(content)
    parser.close()

    assert not parser.errors, f"HTML parse errors encountered: {parser.errors}"

    disclaimer = "The content of this page was generated by AI."
    assert any(disclaimer in comment for comment in parser.comments), "AI disclaimer comment missing"
